### PR TITLE
Moved the import and export button

### LINKED ISSUE #53: Move import and export buttons
We need to move the import and export button in the popup, because the config not only contains settings for trigger, but also for the theme selector.

### PR DESCRIPTION
**Pull request by Nathanymous**
Moved the import and export button
Added some margin to the save and defaults button
Fixes #53

### CODE REVIEW

**Comment by Nathanymous** [comment]
After a quick discussion we decided that all buttons (Save / Defaults / Import / Export) should become icons with onhovers that explains what it does.

**Comment by TargetCrafter** [comment]
I had a look at you design, but it doesn't feel right. I did some playing around, and i think the below design might be a better fit:

normal fileMenu

**Comment by Nathanymous** [comment]
I think this design is much better. You can go on and build this.

**Comment by Nathanymous** [comment]
I am deleting this PR since there is still work needed to create this.
When the changes are made and the code is ready I will make a new PR

**Pull request closed without merging**
